### ISSUE TITLE
No such file or directory: 'datasets/labels_CLIP.npy'

### ISSUE THREAD

**Issue by Vincent-luo** [LLNL/CREPE#3]
When I run the training command:
```
python train_prompter.py --n_contex_vectors 8 --token_position 'middle' --num_predicates 50 \
        --epochs 500 --learning_rate 2e-3 --batch_size 256 \
        --use_cuda True --out_dir './output' --data_dir 'datasets/pred_dicts_train_cmr'
```
I got this error "No such file or directory: 'datasets/labels_CLIP.npy'". After reviewing the code, I found that some files were missing in the `datasets` directory. So how can I get these files? It would be helpful if the directory structure of the `datasets` could be provided.

**Comment by Rakshith-2905** [comment]
Thank you for bringing this to our attention. We will soon update the repository with instructions on how to acquire these files and will also provide a directory structure for the `datasets` folder.

**Comment by stranger957** [comment]
I also encountered the same problem, how to solve this problem

**Comment by Rakshith-2905** [comment]
HAve updated the repo with the dataset
